### ISSUE TITLE
Does not work with me: does not exist!

### ISSUE THREAD

**Issue by eArabic** [phhpro/easy-source#1]
Hello my friend
Thank you very much for this script, but it did not work with me.
![99](https://user-images.githubusercontent.com/24383546/35687404-ac281bd6-077f-11e8-8955-5c3e1a99533c.png)

**Comment by phhpro** [comment]
what's in line #50 of source.php?

**Comment by eArabic** [comment]
**$src_root = $_SERVER['DOCUMENT_ROOT'];**

**Comment by phhpro** [comment]
LOL. Yeah, I know that one :) If I recall correctly, your path would seem a little borked, and that's where line #47 comes into play:      * Full "path" without trailing / if SERVER has wrong value

It helps to read the comments every once in a while. Try changing the path to what you had in Easy Comments. Same server, same path, and remember: no trailing /

**Comment by eArabic** [comment]
Thank you very much, now it works after this edit:
$src_root = "/membri/User/source";
Very excellent, needs some features:
Edit a file with the save feature.
Create a new file.
Simple file browser.

**Comment by phhpro** [comment]
The script's sole purpose is to render a source code view of the given source, e.g. where you want to illustrate the inner workings of a file from a developers point of view. If you need to edit files, I suggest you have a look into [Browser Edit](https://github.com/phhpro/browser-edit), which may be better suited. Regards.
